### ISSUE TITLE
Failed to STOP recording 

### ISSUE THREAD

**Issue by ChaymaBENBRAHIM** [boonya/rtsp-video-recorder#280]
Hi !
I am failed to stop recording
any help
thanks

**Comment by boonya** [comment]
Most likely I am working on this already https://github.com/boonya/rtsp-video-recorder/issues/274

**Comment by boonya** [comment]
But it really depends on root cause of your fail.

**Comment by ChaymaBENBRAHIM** [comment]
Hi @boonya  , 
Can i have a way to talk with you and discuss the probleme ? 
Thanks

**Comment by boonya** [comment]
> Hi @boonya , Can i have a way to talk with you and discuss the probleme ? Thanks

Yes we can but I do not have a time so far. First of all what timezone you live in?

**Comment by ChaymaBENBRAHIM** [comment]
> > Hi @boonya , Can i have a way to talk with you and discuss the probleme ? Thanks
> 
> Yes we can but I do not have a time so far. First of all what timezone you live in?

I live in tunisia,
For the timezone is "UTC +1".
I hope that you  will try to find a time for me to solve the problem :) 
thanks

**Comment by boonya** [comment]
Hey, @ChaymaBENBRAHIM  first of all try version `2.2.0` if it does not help you, let me know how you can talk?

**Comment by ChaymaBENBRAHIM** [comment]
> Hey, @ChaymaBENBRAHIM first of all try version `2.2.0` if it does not help you, let me know how you can talk?

hi @boonya, the probleme resist can you give me your linkedIn account or your skype or your Teams account ...?

**Comment by boonya** [comment]
https://www.linkedin.com/in/boonya/

**Comment by boonya** [comment]
Related to https://github.com/boonya/rtsp-video-recorder/issues/273

**Comment by boonya** [comment]
Conducted an online consultation
