### ISSUE TITLE
rtsp-video-recorder in angular 

### ISSUE THREAD

**Issue by kranthi0987** [boonya/rtsp-video-recorder#29]
core.js:4081 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'native' of undefined
TypeError: Cannot read property 'native' of undefined
    at Object../node_modules/fs-extra/lib/fs/index.js 

`import {MAT_DIALOG_DATA, MatDialogRef} from '@angular/material/dialog';
import {AfterViewInit, Component, ElementRef, Inject, OnChanges, OnInit, Renderer2, SimpleChanges, ViewChild} from '@angular/core';

import {
  FormControl,
  Validators,
  FormGroup,
  FormBuilder
} from '@angular/forms';
import {PatientService} from "../../../allpatient/patient.service";
import {PastVisitModel} from "../../../models/PastVisitModel";
import Recorder, { RecorderEvents } from 'rtsp-video-recorder';

@Component({
  selector: 'app-form-dialog',
  templateUrl: './form-dialogpastvisit.component.html',
  styleUrls: ['./form-dialogpastvisit.component.sass']
})

export class FormDialogPastVisitComponent implements AfterViewInit, OnInit, OnChanges {
  action: string;
  dialogTitle: string;
  patientForm: FormGroup;
  patient: PastVisitModel;
  @ViewChild('video') matVideo: ElementRef<HTMLVideoElement>;
  constructor(
    public dialogRef: MatDialogRef<FormDialogPastVisitComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any,
    public patientService: PatientService,
    private fb: FormBuilder,
  ) {
    const recorder = new Recorder('rtsp://169.254.87.20:554/profile1', '/media/Recorder', {
      title: 'Test Camera',
    });
    // Set the defaults
    this.action = data.action;
    if (this.action === 'view') {
      this.dialogTitle = "View Visit";
      this.patient = data.patient;
    } else {
      this.dialogTitle = 'New Visit';
      this.patient = new PastVisitModel({});
    }
    this.patientForm = this.createContactForm();
  }

  formControl = new FormControl('', [
    Validators.required
    // Validators.email,
  ]);

  getErrorMessage() {
    return this.formControl.hasError('required')
      ? 'Required field'
      : this.formControl.hasError('email')
        ? 'Not a valid email'
        : '';
  }

  createContactForm(): FormGroup {
    return this.fb.group({
      uuid: [this.patient.uuid],
      treatment: [this.patient.treatment],
      consulted_on: [this.patient.consulted_on],
      log_documents: [this.patient.log_documents],
      session_log: [this.patient.session_log],
      // bGroup: [this.patient.bGroup],
      // mobile: [this.patient.mobile],
      // address: [this.patient.address],
      // treatment: [this.patient.treatment]
    });
  }

  submit() {
    // emppty stuff
    this.dialogRef.close();
  }

  onNoClick(): void {
    this.dialogRef.close();
  }

  public confirmAdd(): void {
    this.patientService.addPatient(this.patientForm.getRawValue());
  }

  ngAfterViewInit(): void {
    // set the initial state of the video
    // const matVideo: HTMLVideoElement = this.matVideo.nativeElement;
    this.matVideo.nativeElement.muted = false;
    this.matVideo.nativeElement.controls = true;
    this.matVideo.nativeElement.autoplay = false;

  }

}
`
please help on above error , i am trying to record and save in folder by angular and backend python

Advance thanks.
![Screenshot (1)](https://user-images.githubusercontent.com/8243141/92893385-4074da80-f437-11ea-9a11-527ecd24d680.png)

**Comment by boonya** [comment]
You can not use this library on front end. It's back end only as it required to have `ffmpeg` binary installed as well as `fs-extra` lib. I suppose that your issue is because `fs-extra` tries to interact with file system but there is no such API in your browser environment.
If you want to have it running, you must deploy some simple backend service with `ffmpeg` and `rtsp-video-recorder` installed and configured. Than expose an API to this backend service to your angular frontend application.

**Comment by kranthi0987** [comment]
@boonya  thanks
