### ISSUE TITLE
Import error on RecorderEvent

### ISSUE THREAD

**Issue by yudataguy** [boonya/rtsp-video-recorder#30]
Testing this package with sample code from documentation, but encountered various error regarding import 

```
 Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
```
After insert `"type": "module" in `package.json`, another error pops up
```
import Recorder, { RecorderEvents } from 'rtsp-video-recorder';
                   ^^^^^^^^^^^^^^
SyntaxError: The requested module 'rtsp-video-recorder' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'rtsp-video-recorder';
const { RecorderEvents } = pkg;
```
So follow instruction, I tried out the new import syntax, but
```
const recorder = new Recorder('rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov', '/media/Recorder', {
                 ^
TypeError: Recorder is not a constructor
```

Any suggestion on how to fix this simple looking error, and seems no one else is having this issue.

**Comment by boonya** [comment]
Hello @yudataguy.
To start working on it let me ask you a couple of questions to figure out what the root cause is.

### The first one is - what version of nodejs and npm do you use for it?
```
node --version
npm --version
```

### The second is could I ask you for more details about your environment? E.g. your `package.json` file content

**Comment by boonya** [comment]
Okay, in current situation I can suggest a workaround to try this lib.

```js
const rec = require('rtsp-video-recorder');

const Recorder = rec.default;
const RecorderEvents = rec.RecorderEvents;
```

Later, I am going to handle it somehow

**Comment by boonya** [comment]
> The issue is with
> 
> how ES6 modules are emulated in CommonJS
> how you import the module

https://stackoverflow.com/a/40295288/2512628

If your application structured as a CommonJS module you should be able to import it using

```js
const {Recorder, RecorderEvents, RecorderError, RecorderValidationError} = require('rtsp-video-recorder');
```
So, the only thing I can do s to describe it in the documentation.
