### ISSUE TITLE
Example is not working on Linux, but works on windows.

### ISSUE THREAD

**Issue by decaffeinatedcoffee** [boonya/rtsp-video-recorder#310]
When i run example on windows (11) it works well, the records are saved and its ok, but when i run the same thing on Ubuntu (22.04) nothing happens, the code run with no errors or any output, but the records folder is empty all the time, except when i stop the process, because some seconds after i stop the node process, a single 5 seconds long mp4 file is generated. I need help to understand what is happening.

**Comment by boonya** [comment]
Did you try to run a `ffmpeg` directly?

```bash
ffmpeg -rtsp_transport tcp -i ${YOUR_STREAM_ADDRESS} -reset_timestamps 1 -c:a aac -strftime 1 -strftime_mkdir 1-hls_time 600 -hls_list_size 0 -hls_segment_filename %Y.%m.%d/%H.%M.%S.mp4 ./playlist.m3u8
```

**Comment by decaffeinatedcoffee** [comment]
> Did you try to run a `ffmpeg` directly?
> 
> ```bash
> ffmpeg -rtsp_transport tcp -i ${YOUR_STREAM_ADDRESS} -reset_timestamps 1 -c:a aac -strftime 1 -strftime_mkdir 1-hls_time 600 -hls_list_size 0 -hls_segment_filename %Y.%m.%d/%H.%M.%S.mp4 ./playlist.m3u8
> ```

Yes, same thing happens.

**Comment by boonya** [comment]
So, the issue is not related to the library but to your environment. So far, I have no idea what is wrong there. I am googling...

**Comment by boonya** [comment]
@decaffeinatedcoffee did you resolve your issue somehow? Did you get what it was?

**Comment by decaffeinatedcoffee** [comment]
> @decaffeinatedcoffee did you resolve your issue somehow? Did you get what it was?

unfortunately not ):

**Comment by boonya** [comment]
What version of ffmpeg do you have on your linux system? What version of linux? Is there a network storage or any other variant mounted storage? Docker? Virtual box?
