### ISSUE TITLE
can it be used with react native for android?

### ISSUE THREAD

**Issue by RaiyanKhalil** [boonya/rtsp-video-recorder#37]
I want to get a stream from an IP camera and record the stream and send it to a server. is it possible using this package?

**Comment by boonya** [comment]
Hello @RaiyanKhalil, Not sure it's possible.
Not sure it's possible. This library supposed to be server side one. It spawns ffmpeg process using node.js API.

**Comment by boonya** [comment]
PS. Look at this one https://play.google.com/store/apps/details?id=net.biyee.onvifer

**Comment by boonya** [comment]
> Hey bro! did you managed to make this work on React Native?

Hello. No, this doesn't work like that. It's a node package, so it requires some OS environmet and a Node JS runtime. Which is not the case for any client side solutions like React Js or React native. React is a static javascript bundle at the end.
If you need the functionality the package serves working with a client app, you have to create a server application which your client is going to interact with.
As an example you can look at [meteor-recorder](https://github.com/boonya/meteor-recorder) which is my own utilization of the [rtsp-video-recorder](https://github.com/boonya/rtsp-video-recorder) lib.

**Comment by AlejandroAguilar99** [comment]
> > Hey bro! did you managed to make this work on React Native?
> 
> 
> 
> Hello. No, this doesn't work like that. It's a node package, so it requires some OS environmet and a Node JS runtime. Which is not the case for any client side solutions like React Js or React native. React is a static javascript bundle at the end.
> 
> If you need the functionality the package serves working with a client app, you have to create a server application which your client is going to interact with.
> 
> As an example you can look at [meteor-recorder](https://github.com/boonya/meteor-recorder) which is my own utilization of the [rtsp-video-recorder](https://github.com/boonya/rtsp-video-recorder) lib.

Damn, I'll check it out, thanks for answering!
